### ISSUE TITLE
Why is Sendinblue package set to 2.0.4 ?

### ISSUE THREAD

**Issue by bsuttor** [collective/collective.sendinblue#1]
In setup.py, I see Sendinblue==2.0.4,
can we update with last version of Sendinblue (2.0.5.1) ?

https://pypi.python.org/pypi/Sendinblue

**Comment by laulaz** [comment]
Yes, we can :blush: 
I tested and it works with 2.0.5.1, so I removed the version pin.
Note that on Pypi there is a 2.0.6 tar.gz (see https://pypi.python.org/simple/sendinblue/) but not used as last version (?).

Reopen this issue if you want me to make a release.

**Comment by bsuttor** [comment]
Indeed, I would like a new release, 
I have some buildout issues because of pinned version, but I see I have right on pypi to make a release. So can I make it ?

**Comment by laulaz** [comment]
Be my guest, do it :smiley:

**Comment by bsuttor** [comment]
Done ;)
https://pypi.python.org/pypi/collective.sendinblue/1.0.1
